# Generated by Django 5.2.1 on 2025-06-12 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JumpVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_video", models.FileField(upload_to="videos/")),
                (
                    "processed_video",
                    models.FileField(null=True, upload_to="processed_videos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("left_knee_angle", models.FloatField(null=True)),
                ("right_knee_angle", models.FloatField(null=True)),
                ("left_hip_angle", models.FloatField(null=True)),
                ("right_hip_angle", models.FloatField(null=True)),
                ("left_ankle_angle", models.FloatField(null=True)),
                ("right_ankle_angle", models.FloatField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Note",
        ),
    ]
