# Generated by Django 5.2.1 on 2025-06-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_jumpvideo_delete_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="jumpvideo",
            name="left_shoulder_angle",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="jumpvideo",
            name="right_shoulder_angle",
            field=models.FloatField(null=True),
        ),
    ]
